INSERT INTO Livro (titulo, autor, genero, anoPublicacao, status) VALUES 
('The Great Gatsby', 'F. Scott Fitzgerald', 'Fiction', 1925, 'Available'),
('To Kill a Mockingbird', 'Harper Lee', 'Fiction', 1960, 'Available'),
('1984', 'George Orwell', 'Dystopian', 1949, 'Available'),
('Pride and Prejudice', 'Jane Austen', 'Romance', 1813, 'Available'),
('The Catcher in the Rye', 'J.D. Salinger', 'Fiction', 1951, 'Available'),
('Moby Dick', 'Herman Melville', 'Adventure', 1851, 'Available'),
('War and Peace', 'Leo Tolstoy', 'Historical', 1869, 'Available'),
('The Odyssey', 'Homer', 'Epic', -800, 'Available'),
('Crime and Punishment', 'Fyodor Dostoevsky', 'Psychological', 1866, 'Available'),
('The Brothers Karamazov', 'Fyodor Dostoevsky', 'Philosophical', 1880, 'Available'),
('Anna Karenina', 'Leo Tolstoy', 'Romance', 1877, 'Available'),
('The Hobbit', 'J.R.R. Tolkien', 'Fantasy', 1937, 'Available'),
('Brave New World', 'Aldous Huxley', 'Dystopian', 1932, 'Available'),
('The Divine Comedy', 'Dante Alighieri', 'Epic', 1320, 'Available'),
('Les Misérables', 'Victor Hugo', 'Historical', 1862, 'Available'),
('Ulysses', 'James Joyce', 'Modernist', 1922, 'Available'),
('The Iliad', 'Homer', 'Epic', -750, 'Available'),
('Jane Eyre', 'Charlotte Brontë', 'Romance', 1847, 'Available'),
('The Grapes of Wrath', 'John Steinbeck', 'Historical', 1939, 'Available'),
('One Hundred Years of Solitude', 'Gabriel García Márquez', 'Magical Realism', 1967, 'Available'),
('The Sound and the Fury', 'William Faulkner', 'Modernist', 1929, 'Available'),
('Catch-22', 'Joseph Heller', 'Satire', 1961, 'Available'),
('The Old Man and the Sea', 'Ernest Hemingway', 'Fiction', 1952, 'Available'),
('The Scarlet Letter', 'Nathaniel Hawthorne', 'Historical', 1850, 'Available'),
('Wuthering Heights', 'Emily Brontë', 'Romance', 1847, 'Available'),
('The Picture of Dorian Gray', 'Oscar Wilde', 'Philosophical', 1890, 'Available'),
('The Lord of the Rings', 'J.R.R. Tolkien', 'Fantasy', 1954, 'Available'),
('Don Quixote', 'Miguel de Cervantes', 'Adventure', 1605, 'Available'),
('Fahrenheit 451', 'Ray Bradbury', 'Dystopian', 1953, 'Available'),
('Madame Bovary', 'Gustave Flaubert', 'Realist', 1857, 'Available');
